### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by jayarachelsigamala** [clauswilke/SDS348_spring2020#10]
Hi! I am working on question 1 on homework 8 and I am using question 4 on class 18 worksheet as a guide to solving the problem but when I run the code I don't get any output. 

``` python 
filename = "IL6_gene_human_lower.txt"

infile = open("IL6_gene_human_lower.txt", "r")
lines = infile.readlines()
infile.close()

with open("IL6_gene_human_lower.txt", "r") as infile, \
     open("IL6_gene_human_upper.txt", "w") as outfile:
    for line in infile:
        outfile.write(line.upper())
        
with open("IL6_gene_human_upper.txt", "r") as infile:
    for line in infile:
        print(line.rstrip())

**Comment by clauswilke** [comment]
Your code runs for me. I suspect your file `"IL6_gene_human_lower.txt"` is empty somehow. You can check for that by clicking on it in the Jupyter hub.

<img width="1027" alt="Screen Shot 2020-04-12 at 1 34 18 PM" src="https://user-images.githubusercontent.com/4210929/79076804-7b28ea00-7cc2-11ea-8a81-aeb0fe209d82.png">

**Comment by jayarachelsigamala** [comment]
Okay! I was able to delete and reupload the file and I was able to get a output but I don't think I was able to get rid of the white space.

**Comment by clauswilke** [comment]
If you're not able to get rid of the white space that's a separate issue. Take a look at some of the closed issues on this topic, e.g. #11.
