### ISSUE TITLE
Removing /N , commas and single quotations

### ISSUE THREAD

**Issue by mmmezes** [clauswilke/SDS348_spring2020#11]
I produced a string from the list that was produced by the text file in order to use the string functions to make it uppercase and remove white space, however I am unable to remove the new line characters, commas, single quotations. When I replace readlines() with read().splitlines() it will produce output without the new line characters, but the commas and single quotations remain. 

IL6_gene = "IL6_gene_human_lower.txt"

IL6 = open(IL6_gene, "r") 
IL6_contents = IL6.readlines()
IL6.close() 
IL6_string = str(IL6_contents)
print(IL6_string.upper().strip().rstrip())

It produces output with upper case letters, but includes new line characters, commas and quotations. I'm not sure how to remove them while using readlines() to fead the file.

**Comment by rachaelcox** [comment]
Will you include your output as well, perhaps as a screenshot?

**Comment by clauswilke** [comment]
The function `readlines()` gives you a list, so you need to iterate over every element in a list with a `for` loop. The statement `str(IL6_contents)` is incorrect. Instead you need something like:
``` python
for line in IL6_contents:
    #.... do something here with the variable "line"
```

**Comment by mmmezes** [comment]
> Will you include your output as well, perhaps as a screenshot?

<img width="1094" alt="Screen Shot 2020-04-12 at 2 41 56 PM" src="https://user-images.githubusercontent.com/63559583/79078142-e9be7580-7ccb-11ea-9bea-d9d928b65481.png">

**Comment by mmmezes** [comment]
I reconfigured by code using a for loop, but now I'm not sure how to remove this additional space that has now appeared. 
<img width="1118" alt="Screen Shot 2020-04-12 at 2 48 53 PM" src="https://user-images.githubusercontent.com/63559583/79078282-f55e6c00-7ccc-11ea-921d-15bea7f62dfc.png">

**Comment by clauswilke** [comment]
Strings are not mutable in python, so `line.rstrip()` doesn't modify the string you have in `line`, it just gives you a new string with whitespace removed. You need to assign the result to a new variable and then work with that variable.

**Comment by rachaelcox** [comment]
You can create a new string variable, and then add each formatted line to that string as you loop through the list of lines. Here is an example from lab (https://wilkelab.org/classes/SDS348/2020_spring/labs/lab8-solution.html) where we did a similar thing, except working with a dictionary instead of a list:
![image](https://user-images.githubusercontent.com/42787920/79078334-4d956e00-7ccd-11ea-9501-f936f6b20523.png)

**Comment by mmmezes** [comment]
Got it! Thank you both for the help!
