### ISSUE TITLE
Homework 8

### ISSUE THREAD

**Issue by emm3777** [clauswilke/SDS348_spring2020#12]
I am having trouble opening a file and doing multiple functions to that file
for question 1 I know how to read the sequence line by line by using
`file_lines = file_handle.readlines()`
and I can make it uppercase by doing
`for lines in file_handle:
       lines = lines.upper()
        print(lines)`
but I can't figure out how to put both codes together.

I know how to do question 2 But I am also having trouble opening the file and using the function I have created
I open the file, then I insert the function, then I write
`count_kmers("filename",3)`
and it gives me kmers for the word "filename" and not the actual file contents

If you need to see more of my code let me know.

**Comment by clauswilke** [comment]
Please open two separate issues if you have two separate questions. And yes, you'll have to provide a complete reproducible example and show us a concrete error or incorrect output. Otherwise we don't know what the problem is.

**Comment by emm3777** [comment]
Issue #1 
![Screenshot (3)](https://user-images.githubusercontent.com/63424679/79086245-fdd09a00-7d00-11ea-805e-ea1401ba5945.png)
![Screenshot (4)](https://user-images.githubusercontent.com/63424679/79086251-02954e00-7d01-11ea-81b7-a18698cb6d42.png)

**Comment by rachaelcox** [comment]
You've got a comma after `file_lines = file_handle.readlines()`. Try deleting that, let me know if you still get an error.

**Comment by emm3777** [comment]
I deleted the comma, and the error went away but it is still not capital letters

**Comment by rachaelcox** [comment]
Are you sure? This is your code:
![image](https://user-images.githubusercontent.com/42787920/79086934-6d478900-7d03-11ea-93d5-490f8c5a5361.png)

**Comment by emm3777** [comment]
I had the print(lines) in the wrong place, Thank you I got it to work, I also added the strip() function to take out the spaces and it worked,

**Comment by emm3777** [comment]
I thought when you use readlines() you will see the /n symbol

**Comment by rachaelcox** [comment]
Only if you print the list object itself (in this case, `file_lines`). If you iterate through the list and print each string in the list, then Python will interpret the '\n' instead of printing it and add a new line. Try `print(file_lines)` to see what I mean.

**Comment by emm3777** [comment]
OK that makes sense, Thank You
