### ISSUE TITLE
HW 8 issue 2

### ISSUE THREAD

**Issue by emm3777** [clauswilke/SDS348_spring2020#15]
Issue #2 
![Screenshot (5)](https://user-images.githubusercontent.com/63424679/79086300-31abbf80-7d01-11ea-8d6a-4fc9e166dcc8.png)

**Comment by clauswilke** [comment]
You're counting kmers on the string "filename" instead of on the contents of the file. You need to read in the contents of the file with `file_handle.read()` and then run the `count_kmers()` function on that contents.

**Comment by emm3777** [comment]
I changed it so that the function is running off of the file_contents but now it only shows that each kmer only occurs once
![Screenshot (6)](https://user-images.githubusercontent.com/63424679/79089822-28285480-7d0d-11ea-901d-53366c3c8622.png)

**Comment by clauswilke** [comment]
Carefully compare your counting function to the one we had in class 16:
https://wilkelab.org/classes/SDS348/2020_spring/slides/class16.pdf

**Comment by TongruiLi** [comment]
The increment of the dictionary has the wrong indention
