### ISSUE TITLE
HW9 question 3 issue

### ISSUE THREAD

**Issue by cag137** [clauswilke/SDS348_spring2020#17]
Hello!

I'm currently dealing with question 3 of HW9. The code below works perfectly when I set `retmax` < 50 in the previous question. This is, when `len(pmid_list)` is below 50. However, when I set `retmax` at 100 as requested, the code stops working and I get 

**The Error**
> KeyError                                  Traceback (most recent call last)
<ipython-input-139-e62400f5aee6> in <module>
      8 
      9 for record in records:
---> 10     match = re.search("evolution(|ary)",record["AB"])
     11     if match:
     12         count += 1
KeyError: 'AB'

**The Code**
```Python
import re
from Bio import Medline
Entrez.email = "email@utexas.edu" 

handle = Entrez.efetch(db = "pubmed", id = pmid_list, rettype = "medline", retmode = "text")
records = Medline.parse(handle)
count = 0

for record in records:
    match = re.search("evolution(|ary)",record['AB'])
    if match:
        count += 1
        
print(count)  
    
handle.close()
```

I have no idea why the code depends on the for loop size. What am I doing wrong?

Thank you!

**Comment by rachaelcox** [comment]
I recommend only initiating the regex search if the record contains an abstract (perhaps not all do?). By this I mean:

```python
for record in records:
    if 'AB' in record:
        match = re.search("evolution(|ary)",record['AB'])
        if match:
            count += 1
```
Or something like that. Let me know if you still get the error!

**Comment by clauswilke** [comment]
Yes, this is the problem. There are a few records without abstract, but they are rare. As a result, everything works fine for the first 50 records but then things go bad for some later record.

**Comment by cag137** [comment]
In fact, now it works.

Thank you very much!
