### ISSUE TITLE
Homework 9, Question #3

### ISSUE THREAD

**Issue by jaymatrob** [clauswilke/SDS348_spring2020#20]
`handle = Entrez.esearch(
    db="pubmed",
    term="Arnold FH[Author] AND 2015, 2016, 2017, 2018, 2019[Date - Publication]",
    retmax=100)
record = Entrez.read(handle)
handle.close()

pmid_list = record["IdList"]

import re
Entrez.email = "jmrobinson@utexas.edu" # put your email here

handle = Entrez.efetch(db="pubmed", id=pmid_list, rettype="medline", retmode="text")
records = Medline.parse(handle)

for record in records:
    match = re.search(r"evolutio(n|nary)", record['AB'])
    if match:
        print(record['TI'])`

I keep getting this error: "Key Error: 'AB'", and I am not really sure how to fix it since I am still getting printed titles.

**Comment by clauswilke** [comment]
Could you please put your code into three backticks so it's formatted correctly, as shown here: https://github.com/clauswilke/SDS348_spring2020/blob/master/README.md#asking-questions-about-python

And please copy the entire error message, again as shown in the example I linked to.

**Comment by jaymatrob** [comment]
```
from Bio import Entrez, Medline
Entrez.email = "jmrobinson@utexas.edu" # put your email here

handle = Entrez.esearch(
    db="pubmed",
    term="Arnold FH[Author] AND 2015, 2016, 2017, 2018, 2019[Date - Publication]",
    retmax=100)
record = Entrez.read(handle)
handle.close()

pmid_list = record["IdList"]

import re
Entrez.email = "jmrobinson@utexas.edu" # put your email here

handle = Entrez.efetch(db="pubmed", id=pmid_list, rettype="medline", retmode="text")
records = Medline.parse(handle)

for record in records:
    match = re.search(r"evolutio(n|nary)", record['AB'])
    evol = []
    if match:
        evol.append(record['TI'])
---------------------------------------------------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-47-5ebd7cf108a8> in <module>
      7 
      8 for record in records:
----> 9     match = re.search(r"evolutio(n|nary)", record['AB'])
     10     evol = []
     11     if match:

KeyError: 'AB'
```

**Comment by clauswilke** [comment]
Thanks! This looks exactly like issue #17, which has been answered.
