### ISSUE TITLE
Hw 9 Q1

### ISSUE THREAD

**Issue by jennifernadasdy** [clauswilke/SDS348_spring2020#21]
This is my code so far:

```{python}
# you will need Entrez and SeqIO to solve this problem
from Bio import Entrez, SeqIO
Entrez.email = "myemail@utexas.edu" # put your email here

handle = Entrez.efetch(db="pubmed", id="NC_045512", rettype="medline", retmode="text")
record = SeqIO.read(handle, "genbank")
handle.close()

print(record)
```

This is the error message:

ValueError                                Traceback (most recent call last)
<ipython-input-4-906d3497d7ed> in <module>
      4 
      5 handle = Entrez.efetch(db="pubmed", id="NC_045512", rettype="medline", retmode="text")
----> 6 record = SeqIO.read(handle, "genbank")
      7 handle.close()
      8 

/opt/anaconda3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py in read(handle, format, alphabet)
    746         first = None
    747     if first is None:
--> 748         raise ValueError("No records found in handle")
    749     try:
    750         second = next(iterator)

ValueError: No records found in handle

I don't really know how to download the GenBank record associated with SARS-CoV-2 if this is not working. What's wrong with this? How can I fix it?

**Comment by clauswilke** [comment]
Why did you set `rettype="medline"` in your `efetch()` query? You need `rettype="gb"` to retrieve a genbank record.

**Comment by jennifernadasdy** [comment]
Thank you. The next line in the class for a similar problem was : 
```{python}
record = SeqIO.read(handle, "genbank")
```

Using this line for hw also gave me an error:

ValueError                                Traceback (most recent call last)
<ipython-input-5-57b012bddd5c> in <module>
      4 
      5 handle = Entrez.efetch(db="pubmed", id="NC_045512", rettype="gb", retmode="text")
----> 6 record = SeqIO.read(handle, "genbank")
      7 handle.close()
      8 

/opt/anaconda3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py in read(handle, format, alphabet)
    746         first = None
    747     if first is None:
--> 748         raise ValueError("No records found in handle")
    749     try:
    750         second = next(iterator)

ValueError: No records found in handle

What is wrong here?

**Comment by clauswilke** [comment]
Ah, you're also querying the wrong database. You need `db="nucleotide"`.

**Comment by jennifernadasdy** [comment]
Thank you! It's working now. :)
