### ISSUE TITLE
HW 9 Q1

### ISSUE THREAD

**Issue by jennifernadasdy** [clauswilke/SDS348_spring2020#22]
Unfortunately, I don't understand Q1. 
Here is the problem:
Then, for each CDS in the record, print the locus tag and the name of the protein product associated with the gene at that locus.

What are the CDS record and locus tag?

I can't get any part of this text. I tried:
```{python}
record['Seq']

record['Description']
```

I have 2 problems: 
1. I can't get anything out of this file
2. I don't really understand what my goal is. 

How can I get CDS out of the file?

This is what we did in the class and I belive this is what I should use to solve this problem:

```{python}
features = record['GBSeq_feature-table'] # extract all the features
for feature in features: # loop over features and find CDS feature
    if feature['GBFeature_key']=='CDS':
       quals = feature['GBFeature_quals']
       for q in quals:
            print(q['GBQualifier_name'])
```

**Comment by jennifernadasdy** [comment]
So this worked:

```{r}
print("\n- The sequence in this record:")
print(record.seq)
```

I belive the prevoius examples are for dictionaries and this one is not a dictionary.

**Comment by rachaelcox** [comment]
Hi Jennifer,

We actually went over **two ways** to parse this file in class: (1) by retrieving the record in text format and parsing with Biopython's SeqIO, or (2) by retrieving the record in XML format and parsing it with Entrez. I think you're getting your wires crossed, but I can't be sure since I don't see all of your code.

If you did (1), then this is the example code you should consult (problem 2):
https://wilkelab.org/classes/SDS348/2020_spring/worksheets/class20_solutions.html

If you did (2), then this is what you should reference (problem 1b):
https://wilkelab.org/classes/SDS348/2020_spring/worksheets/class21_solutions.html

**Comment by rachaelcox** [comment]
Also, your goal is extract all of the proteins that the SARS-CoV-2 genome codes for (CDS = coding sequence) from the file.

**Comment by jennifernadasdy** [comment]
Now my main problem is that I don't understand the problem itself.
There is no CDS or locus in the file. I just did a search for those words. I thought I need to get and print out parts of the file but I can't find anything in the file that seems relevant. I don't know the meaning of words such as locus or CDS. Can you please give me a context?

**Comment by jennifernadasdy** [comment]
I can get the sequence.

**Comment by jennifernadasdy** [comment]
- The sequence in this record:
ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTTAAAATCTGTGTGGCTGTCACTCGGCTGCATGCTTAGTGCACTCACGCAGTATAATTAATAACTAATTACTGTCGTTGACAGGACACGAGTAACTCGTCTATCTTCTGCAGGCTGCTTACGGTTTCGTCCGTGTTGCAGCCGATCATCAGCACATCTAGGTTTCGTCCGGGTGTGACCGAAAGGTAAGATGG.....

**Comment by jennifernadasdy** [comment]
This is not what I need, right?

**Comment by rachaelcox** [comment]
You don't want the sequences, just the annotation. For instance, in https://wilkelab.org/classes/SDS348/2020_spring/worksheets/class20_solutions.html, problem 2 shows an example of printing a locus tag (which is just an arbitrary name for the gene location) and protein product (this is what the gene codes for, e.g., a capsid protein).

**Comment by jennifernadasdy** [comment]
Thank you. I take another look at that lecture again. I think I just don't have enough biology background to understand the goal of these problems. :)

**Comment by rachaelcox** [comment]
This question does assume a bit of biology background! During next week's lab I will expand on the goal and how programmatic access to this information is useful for research :)

**Comment by jennifernadasdy** [comment]
Is this the desaired output?

GU280_gp01: ORF1ab polyprotein
GU280_gp01: ORF1a polyprotein
GU280_gp02: surface glycoprotein
GU280_gp03: ORF3a protein
GU280_gp04: envelope protein
GU280_gp05: membrane glycoprotein
GU280_gp06: ORF6 protein
GU280_gp07: ORF7a protein
GU280_gp08: ORF7b
GU280_gp09: ORF8 protein
GU280_gp10: nucleocapsid phosphoprotein
GU280_gp11: ORF10 protein

**Comment by clauswilke** [comment]
Yes, this looks correct.
