### ISSUE TITLE
hw 9 question 3

### ISSUE THREAD

**Issue by sahmad998** [clauswilke/SDS348_spring2020#24]
i think i got the top half of the code correct, but when i actually try to pull up the abstract info, i'm getting an error...what am i doing wrong?
``` python
parsed = Medline.parse(handle)
records = list(parsed)[0]

lit_dict = {}
for record in records:
    print(record['AB'])
```

this is the error i'm getting: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-96d26e1520ec> in <module>
     15 lit_dict = {}
     16 for record in records:
---> 17     print(record['AB'])
     18 
     19 # your code here

TypeError: string indices must be integers
```

**Comment by clauswilke** [comment]
Why did you add `[0]` after `list(parsed)`?

**Comment by sahmad998** [comment]
i thought [0] would give us the first element of the parsed list, so maybe i could see what that element was and then further divide it when i did the print function

**Comment by rachaelcox** [comment]
It's from problem 1 in https://wilkelab.org/classes/SDS348/2020_spring/labs/lab11-solution.html, but that code was specific to printing out the elements of a single PMID. For HW9-3 (which uses a list of IDs saved to the variable `pmid_list`), try:

```python
handle = Entrez.efetch(db="pubmed", id=pmid_list, rettype="medline", retmode="text")
records = Medline.parse(handle)
for record in records:
    # check if a record has an abstract
    if "AB" in record:
        print(record['AB'])
```
