### ISSUE TITLE
HW 9 problem 3

### ISSUE THREAD

**Issue by mmmezes** [clauswilke/SDS348_spring2020#25]
I successfully parsed the results of the literature search and was able to print the abstracts. I'm now wondering how to convert these abstracts into a string for the regular expression to process. I have code written that gives me the following output but I'm not sure if this is correct way to do this? And then as far as counting the number of abstracts that do match for the selected terms goes, I'm not quite sure where to start.
input:
handle = Entrez.efetch(db="pubmed", id=pmid_list, rettype="medline", retmode="text")
records = Medline.parse(handle)
for record in records:
    if "AB" in record:
        AB_list = record['AB']
        match = re.search(r"evolutio(n|nary)", AB_list)
        if match:    
            print("AB matches.")
            print("Match:", match.group()) 
        else:
            print("AB doesn't match")
output:
AB matches.
Match: evolution
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB doesn't match
AB doesn't match
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB doesn't match
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB doesn't match
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB doesn't match
AB doesn't match
AB matches.
Match: evolution
AB doesn't match
AB doesn't match
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution
AB doesn't match
AB doesn't match
AB matches.
Match: evolution
AB doesn't match
AB matches.
Match: evolution
AB matches.
Match: evolution

**Comment by clauswilke** [comment]
Please check out issue #17. It should have all answers you need.

Also, in the future, please format your code by enclosing it in three backticks, as [explained here.](https://github.com/clauswilke/SDS348_spring2020/blob/master/README.md#asking-questions-about-python) Otherwise the indentation gets messed up and it's not possible to assess whether the code is correct or not.
