### ISSUE TITLE
HW 9 Question 2

### ISSUE THREAD

**Issue by ut-compbio** [clauswilke/SDS348_spring2020#26]
I wrote the following code to answer question 2 and figured I would check my answer by using similar code to only look at the years individually and then add the number of publications from each year by hand. When I checked the code in this way, the final number of publications from 2015 to 2019 was 68. However, when I run the following code, it says the total number of publications from 2015 to 2019 is 62. I'm not quite sure what is causing this discrepancy. 

```python
handle = Entrez.esearch(
    db="pubmed",  
    term="Arnold FH[Author] AND 2015, 2016, 2017, 2018, 2019[Date - Publication]", 
    retmax=100)
record = Entrez.read(handle)
handle.close()

pmid_list = record["IdList"]
print("Publications found:", pmid_list)
print("Number of publications from 2015 to 2019:", len(pmid_list))
```
The output is as follows:
`Publications found: ['31938573', '31790588', '31747522', '31611694', '31611634', '31513332', '31433107', '31308553', '31187993', '31073063', '31070908', '30979809', '30930550', '30834315', '30600873', '30568304', '30372623', '30343008', '30280154', '30215880', '30025465', '29946033', '29933431', '29712420', '29651849', '29632883', '29622650', '29584811', '29186119', '29170950', '29064156', '29059183', '29026041', '28721734', '28711855', '28708383', '28644476', '28286694', '28283661', '28262559', '27935677', '27885032', '27648601', '27573353', '27510733', '27493686', '27355405', '27102675', '26986867', '26970325', '26644020', '26553994', '26537398', '26512129', '26502343', '26405689', '26299431', '26211362', '26038227', '25849365', '25649694', '24979679']
Number of publications from 2015 to 2019: 62`

**Comment by clauswilke** [comment]
Without seeing the code that produces an answer of 68 I can't comment on what the difference between the two approaches is.

**Comment by clauswilke** [comment]
In general, though, I would suggest you look at the list of PMIDs that you get, see which ones are present in both scenarios and which ones are not, and then try to understand why the specific publications are missing.

**Comment by ut-compbio** [comment]
Essentially I used the following code for each of the 5 years and then wrote down the output for each and added the number of publications together to check the work. 

```python
handle = Entrez.esearch(
    db="pubmed",  
    term="Arnold FH[Author] AND 2015[Date - Publication]", 
    retmax=100)
record = Entrez.read(handle)
handle.close()

pmid_list = record["IdList"]
print("Publications found:", pmid_list)
print("Number of publication", len(pmid_list))
```
output:
`Publications found: ['26644020', '26553994', '26537398', '26512129', '26502343', '26405689', '26299431', '26211362', '26038227', '25849365', '25649694', '24979679']
Number of publication 12`
 I will try and go through the output to find the IDs that are included when I do each year individually. Is the code where I wrote out each year separated by commas correct? Or is there a different way to include all 5 years in the query?

**Comment by clauswilke** [comment]
I would use this query:
```
Arnold FH[Author] and (2015[Date - Publication] : 2019[Date - Publication]) 
```
It gives me 62 hits on the pubmed website: https://www.ncbi.nlm.nih.gov/pubmed/?term=Arnold+FH%5BAuthor%5D+and+(2015%5BDate+-+Publication%5D+%3A+2019%5BDate+-+Publication%5D)

**Comment by vylan-4228** [comment]
Dr. Wilke, I clicked on the link you sent above and looked at the search results; it seems that one of the 62 hits is actually an article from 2020. So should there actually only be 61 hits in total?

**Comment by clauswilke** [comment]
You're overthinking this. The learning goal is to recreate an interactive search from python. As long as you get the same results you would have gotten on the website that's good enough.

The paper you're concerned about has an official publication date of 2020 but was first published online on November 18 2019: https://www.ncbi.nlm.nih.gov/pubmed/31513332
