### ISSUE TITLE
XML Format Visualization

### ISSUE THREAD

**Issue by jkvilla** [clauswilke/SDS348_spring2020#27]
Has anyone found a useful visualization for the record that get out of `Entrez.efetch(retmode = "xml")` and `Entrez.parse()` functions when pulling a genbank sequence in the xml format (using the following code):

```python
handle = Entrez.efetch(db="nucleotide", id="KT220438", rettype="gb", \
retmode="xml")
parsed = Entrez.parse(in_handle) # use Entrez.parse() to parse
record = list(parsed)[0] # Need to convert into list and get 1st element
handle.close()
print(record)
```

I'm having a hard time understanding what exactly is in all the different dictionaries and lists that get from this code (and which dictionary need to look at for what value). So if anyone has a way to think of it (or a visualization) that would be very helpful.

**Comment by clauswilke** [comment]
I'm not sure there's a good way other than drilling down step by step, i.e., at each step looking at all the keys in a dictionary, finding the ones that look interesting, seeing what values are associated with those keys, etc.

**Comment by jkvilla** [comment]
Okay--I'll look more in detail at each step then. Thanks!
