### ISSUE TITLE
Project 3, part 1

### ISSUE THREAD

**Issue by cag137** [clauswilke/SDS348_spring2020#29]
Hello!

According to the code I wrote for the first part of project 3, 662 PubMed entries contain the keyword in the title; of those, all contain a ['DP'] feature. However, when I use regex to capture publication years, I only got 640 counts. I already checked using  'https://pythex.org/ ' my regex, and it captures the year for both formats provided in the assignment (i.e., 2017 Feb 12 and Winter 2017)... are date formats other than those?

Thank you.

**Comment by rachaelcox** [comment]
Ah, the examples were not meant to be comprehensive. Some will just be the year by itself `2017`, some have the year and a multi-month combo such as `2017 Jan-Mar`, and some will have a 'DP' feature but no date filled in. I recommend printing all your `record['DP']` output to a list or file and checking it out yourself!

**Comment by cag137** [comment]
Thank you @rachaelcox! In fact, the remaining articles have "2020" (year by itself).
