### ISSUE TITLE
homework 10 question 1

### ISSUE THREAD

**Issue by sahmad998** [clauswilke/SDS348_spring2020#30]
i was a bit confused on the instructions and wanted to ask if this was the answer we're looking for (this is what i got based on my code):
```
RecName: Full=Titin; AltName: Full=Connectin; AltName: Full=Rhabdomyosarcoma antigen MU-RMS-40.14
```
when i looked up Q8WZ42 in the NCBI database, this is the name that came up. is this the answer we're looking for, or are we looking to get Q8WZ42 itself as a returned value?

**Comment by rachaelcox** [comment]
We're simply looking to extract `Q8WZ42` from the string `>sp|Q8WZ42|TITIN_HUMAN` (and `A0A060A0J8` from `>tr|A0A060A0J8|A0A060A0J8_XENLA` as well). No extra database query is necessary :)

**Comment by sahmad998** [comment]
is this the correct approach then?
```
import re

match = re.search(r"Q8WZ42", titin_human)
if match: 
    print("Test string matches.")
    print("Match:", match.group())
else:
    print("Test string doesn't match.")
```

**Comment by rachaelcox** [comment]
Negative, you want to write one regular expression that can extract the identifier from any string in the the given UniProt format. In other words, given any string in the format `letters|identifier|organism`, you should write one regex that can extract `identifier`.
