### ISSUE TITLE
Homework 10 Question 2

### ISSUE THREAD

**Issue by utcompbio** [clauswilke/SDS348_spring2020#31]
I'm not sure if I'm going about question 2 in the right way. Is it sufficient to create two separate loops, one that searches for "tRNA" and counts and then another that searches for "rRNA" and counts or is that not considered to be using regular expressions?

**Comment by clauswilke** [comment]
The idea was to do it in one loop and write a regular expression that matches both.

**Comment by utcompbio** [comment]
So are we counting the number of tRNA and rRNAs in total? Or are we supposed to have separate totals for each?

**Comment by clauswilke** [comment]
The intent was to only find the total count. I agree the problem statement isn't entirely clear on this.

**Comment by utcompbio** [comment]
Okay, thank you for clarifying. I'm still struggling a little with the problem itself, and not sure where I am going wrong. When I run a search for "tRNA" and "rRNA" separately I get 439 and 779 matches each, but when I search for "t?r?RNA" I get 864, which should not be the total based on the two separate numbers. 

```p
from Bio import Entrez

Entrez.email = "wilke@austin.utexas.edu" # put your email here

# download Microcystic aeruginosa genome & save it locally:
with open("Maeruginosa.gb", "w") as outfile:
    handle = Entrez.efetch(db="nucleotide", id="NC_010296", rettype="gbwithparts", retmode="text")
    data = handle.read()
    outfile.write(data)
    handle.close()
max_i = 6000
i = 0
RNA_count = 0
for feature in record.features:
    if feature.type == 'CDS':
        i += 1    
        if "product" in feature.qualifiers:
            product = feature.qualifiers["product"][0]
            
            match = re.search(r"^[t?r?RNA]", product)
            if match:
                RNA_count += 1

    if i >= max_i:
        break
print(RNA_count)
```

**Comment by clauswilke** [comment]
Your regular expression is wrong. Please test it out in https://pythex.org/ to see what's happening.

**Comment by rachaelcox** [comment]
Your expression is wrong, but equally as important, it's also in the wrong place. Both rRNA and tRNA will be a feature type, so that's the field you want to search (i.e., you don't want to match CDS).

**Comment by scottburns1082** [comment]
Hi, 

I am confused on this step as well. What can I do differently? 


 

from Bio import Entrez
 Entrez.email = "email@utexas.edu" 

    with open("Maeruginosa.gb", "w") as outfile:
    handle = Entrez.efetch(db="nucleotide", id="NC_010296", rettype="gbwithparts", 
     retmode="text")
    data = handle.read()
    outfile.write(data)
    handle.close()
    
 max_i = 6000
 i = 0
   rna_count = 0
  for feature in record.features:
     if feature.type == '[tTrR]RNA':
            i += 1    
  if "product" in feature.qualifiers:
      product = feature.qualifiers["product"][0]
            
            match = re.search(r"[tTrR]RNA", product)
            if match:
                rna_count += 1

    if i >= max_i:
        break
print(rna_count)

**Comment by clauswilke** [comment]
This line is where things start going wrong:
``` python
if feature.type == '[tTrR]RNA':
```
You need to do a regular expression search against `feature.type`, not a string comparison. You're looking for features of type `[tTrR]RNA`, but such features do not exist. The features are either `tRNA` or `rRNA`.

The part with the product is not needed at all.

**Comment by rachaelcox** [comment]
Hey Scott! Similar problem as I mentioned in my previous comment: you want to search `feature.type` for tRNA and rRNA, not the `feature.qualifier`. You'll also need to implement `re.search` when looking for a match, Python won't recognize a regex outside of that format.

**Comment by utcompbio** [comment]
I checked on pythex and I think I figured out the right general expression but now I'm confused with the order. I understand that we don't need to match CDS or use the product part, so can we just remove those lines of code? This is the code I currently have.

```p 
from Bio import Entrez
Entrez.email = "wilke@austin.utexas.edu" # put your email here
# download Microcystic aeruginosa genome & save it locally:
with open("Maeruginosa.gb", "w") as outfile:
    handle = Entrez.efetch(db="nucleotide", id="NC_010296", rettype="gbwithparts", retmode="text")
    data = handle.read()
    outfile.write(data)
    handle.close()
import re
from Bio import SeqIO
in_handle = open("Maeruginosa.gb", "r")
record = SeqIO.read(in_handle, "genbank")
features = record.features
in_handle.close()
max_i = 20000
i = 0
RNA_count = 0
for feature in record.features:
    match = re.search(r"tRNA|rRNA", feature.type)
    if match:
        RNA_count += 1

    if i >= max_i:
        break
print(RNA_count)
```

**Comment by clauswilke** [comment]
Yes, that's it.
