### ISSUE TITLE
Homework 10 Question 1

### ISSUE THREAD

**Issue by jiwanisahil** [clauswilke/SDS348_spring2020#33]
I was able to extract the middle group from the text but I'm not sure how to remove the second line ( | ). My code and results are below.
```
def extract_middle_group(identifier):
    match = re.search(r"\^|[0-9A-Z](.+?\W)", identifier)
    if match:
        print("The UniProt ID of", identifier, "is", match.group(0))
    return
                      
extract_middle_group(titin_human)
extract_middle_group(lysozyme_frog)```

The UniProt ID of >sp|Q8WZ42|TITIN_HUMAN is Q8WZ42|
The UniProt ID of >tr|A0A060A0J8|A0A060A0J8_XENLA is A0A060A0J8|

**Comment by clauswilke** [comment]
Your regular expression has numerous problems. I'm not sure why it works at all. Please try it out in https://pythex.org/ and make sure you understand every piece of it. For example, this part `\^|` at the beginning means "match the character `^` or something else" and I'm not sure you intend to do this. The identifiers never contain the character  `^`.

I also encourage you to visualize your regular expression in https://regexper.com/ to make sure you understand how it works. This is the visualization for your regex:
<img width="473" alt="Screen Shot 2020-04-25 at 11 33 34 PM" src="https://user-images.githubusercontent.com/4210929/80297919-49e1fc80-874d-11ea-95cf-48095e479004.png">

**Comment by clauswilke** [comment]
Two more comments:

1. Carefully read the hint provided with Problem 1. You're not currently using the hint.
2. You will want a regex that visualizes to something like the following:
<img width="573" alt="Screen Shot 2020-04-25 at 11 39 21 PM" src="https://user-images.githubusercontent.com/4210929/80297983-25d2eb00-874e-11ea-92e6-8a0fc56d2646.png">

**Comment by jiwanisahil** [comment]
Thank you for the help. Alright I got the correct regex now since I was able to match the same picture above on https://regexper.com/. 

```match = re.search(r"\|(.+?)\|", identifier)```

Is it okay for the vertical lines to still be there or am I supposed to remove them as well?

Right now I am getting: |Q8WZ42| and |A0A060A0J8|

**Comment by clauswilke** [comment]
The vertical lines are supposed to be gone. I assume you're using the `.group()` function incorrectly. Please look at the documentation/examples: https://docs.python.org/3/library/re.html#re.Match.group

**Comment by jiwanisahil** [comment]
Got it, thank you!
