### ISSUE TITLE
Project 3 Problem 1

### ISSUE THREAD

**Issue by avni-g** [clauswilke/SDS348_spring2020#34]
I'm struggling with problem 1.2, (how many publications were published per year with the term SARS-Cov-2" in the title?) 

To solve this, I first created a list that extracted all of the matches to 'SARS-CoV-2" in the title. 

```
from Bio import entrez, Medline
Entrez.email = "myemail@utexas.edu" #used my actual email on the project
import re

handle = Entrez.esearch(
        db = "nucleotide",
        term = "SARS-CoV-2['Title']",
        retmax = 10000)

record = Entrez.read(handle)
handle.close()

cov_list = record["IdList"]
print(cov_list)
```

When I printed the list, I got a list of IDs (below is a condensed example version of the output) so I assumed it was working. 

```
['1834376741', '1834376728', '1834376715', '1834376702', '1834376689', '1834376676', '1834376663', '1834376650', '1834376637', '1834376624', '1834376611', '1834376598']
```

The problem is as follows: when I use this list to try and extract date of publication, the counter doesn't work. I know the regular expression (2020) is not correct; I was using it to ensure that there was output from this counter.  

```
import re

handle2 = Entrez.efetch(db = "pubmed", id=cov_list, rettype="medline")
records = Medline.parse(handle2) 

dp_count = 0
for record in records:
    if "DP" in record:
        match = re.search(r"(2020)", record['DP']) #regular expression is a filler expression to ensure there's some output
        if match:
            dp_count += 1
            
handle2.close()

print(dp_count)
```
Output: 

```
0
```

I don't know if there is a mistake in my code or if I'm approaching the problem entirely incorrectly. Any help would be appreciated, thank you!

**Comment by rachaelcox** [comment]
In the first part where you perform the literature search, you should be searching `db = "pubmed"`. Not `db = "nucleotide"`. Try changing that and let me know if you're still having issues!

**Comment by scottburns1082** [comment]
Hello,

I was wondering on how to go about appropriately creating a regular expression for 2020  and 2019. Do we need multiple loops or one regular expression?  
This is what I currently have for 2020:  
 "\b(2020)"

**Comment by rachaelcox** [comment]
Just one regular expression. Check out this cheat sheet: https://www.debuggex.com/cheatsheet/regex/python. 

If `\d` matches one digit, and you want to match four digits (the format of the year), how would you go about doing that? Check your expression on this website by writing in different years (2020, 2009, 1999, etc) as the test string: https://pythex.org/
