### ISSUE TITLE
Project 3, Question 1

### ISSUE THREAD

**Issue by ut-compbio** [clauswilke/SDS348_spring2020#35]
I think for the most part my code is correct for the part of the question that asks to find the number of publications per year for the specific title term. However, when it prints the results, the years are not in chronological order. Is there a way to fix this or is the output given sufficient for the question?

``` python
year_dict2 = {}
for record in records:
    if "DP" in record:
        match = re.search(r"(19..|20..)", record['DP'])
        if match: 
            year = match.group(1)
            if year in year_dict2:
                year_dict2[year] += 1
            else:
                year_dict2[year] = 1
handle1c.close()

print("Year \tNumber of Publications Published")
for key in year_dict2:
    print(key, "\t", year_dict2[key])
```
Output:
```
Year 	Number of Publications Published
2020 	 77
2019 	 229
2018 	 199
2017 	 215
2016 	 278
2015 	 395
2014 	 494
2009 	 895
2013 	 762
2010 	 1740
2012 	 1190
2006 	 13
2011 	 1768
2008 	 33
2007 	 18
2005 	 3
1997 	 8
2004 	 8
2003 	 12
1999 	 4
1998 	 7
2002 	 10
2001 	 8
2000 	 7
1996 	 4
1995 	 8
1994 	 4
1993 	 21
1992 	 8
1991 	 19
1990 	 12
1989 	 16
1988 	 9
1987 	 19
1986 	 32
1985 	 17
1984 	 17
1983 	 25
1982 	 19
1981 	 31
1980 	 33
1979 	 27
1978 	 17
1973 	 2
```

**Comment by rachaelcox** [comment]
There are ways to sort it (https://www.saltycrane.com/blog/2007/09/how-to-sort-python-dictionary-by-keys/), but this is sufficient!

**Comment by ut-compbio** [comment]
Great! Thanks!

**Comment by sahmad998** [comment]
I have a question about this- for the first part of the H1N1 question,  I got 8,713 papers, but for the next part I'm somehow getting a total of 10,000? I've looked over it multiple times and can't figure out where I'm going about it wrong:

```
handle_four = Entrez.efetch(
    db = "pubmed",
    id=h1n1_list,
    rettype="medline")

records = Medline.parse(handle_four) 

total_year = {}
for record in records:
    if "DP" in record:
        match = re.search(r"(19..|20..)", record['DP']) 
        if match:
            year = match.group(1)
            if year in total_year:
                total_year[year] += 1
            else:
                total_year[year] = 1
            

print("Year \tNumber of Publications Published")
for key in total_year:
    print(key, "\t", total_year[key])
```
The results are:
```
Year 	Number of Publications Published
2020 	 343
2019 	 834
2018 	 930
2006 	 2
2017 	 897
2016 	 1035
2015 	 1197
2014 	 1420
2013 	 1728
2009 	 3
2011 	 42
2012 	 1567
2010 	 2
```

**Comment by ut-compbio** [comment]
This might not be the issue, but maybe try closing handle_4 before printing? Mine adds up the second time to 8,713 and the only big difference I see between our codes is that yours doesn't include a line to close the handle.

**Comment by sahmad998** [comment]
> This might not be the issue, but maybe try closing handle_4 before printing? Mine adds up the second time to 8,713 and the only big difference I see between our codes is that yours doesn't include a line to close the handle.

i tried that but nothing changed. thanks though!

**Comment by clauswilke** [comment]
@sahmad998 How many records do you have in your `h1n1_list`? You can find that out by running `print(len(h1n1_list))`. The problem may be above the code you are showing us here, e.g. an incorrect pubmed search.

**Comment by sahmad998** [comment]
@clauswilke Here's what I have for the entirety of the H1N1 section, which gave me a total of 8,714 papers. 
```
Question 1.3
Entrez.email = "saher.fatima98@utexas.edu"
handle_three = Entrez.esearch(
    db = "pubmed", 
    term= "H1N1[Title]", 
    retmax = 10000)

record = Entrez.read(handle_three)
handle_three.close()

h1n1_list = record["IdList"]
print(len(h1n1_list))

print(len(h1n1_list), "papers in total have the term H1N1 in the title.")
```
```
8714
8714 papers in total have the term H1N1 in the title.
```
However, I added a chunk just below the original and did the print(len(h1n1_list)) as you suggested, and got 10,000 papers...which is weird, since one section is giving me 8,714 and another is giving me 10,000.
```
print(len(h1n1_list))
```
```
10000
```
Again, here is the problem part of the code:
```
handle_three = Entrez.esearch(
        db = "pubmed",
        term = "H1N1['Title']",
        retmax = 10000)

record = Entrez.read(handle_three)
handle_three.close

h1n1_list = record["IdList"]

handle_four = Entrez.efetch(
    db = "pubmed",
    id=h1n1_list,
    rettype="medline")

records = Medline.parse(handle_four) 

total_year = {}
for record in records:
    if "DP" in record:
        match = re.search(r"(19..|20..)", record['DP']) 
        if match:
            year = match.group(1)
            if year in total_year:
                total_year[year] += 1
            else:
                total_year[year] = 1
            
handle_four.close()

print("Year \tNumber of Publications Published")
for key in total_year:
    print(key, "\t", total_year[key])
```
The results from this are:
```
Year 	Number of Publications Published
2020 	 343
2019 	 834
2018 	 930
2006 	 2
2017 	 897
2016 	 1035
2015 	 1197
2014 	 1420
2013 	 1728
2009 	 3
2011 	 42
2012 	 1567
2010 	 2
```

**Comment by rachaelcox** [comment]
Change `['Title']` to `[Title]` in the problem search (i.e., remove the quotes). The database doesn't recognize `'Title'` as a valid search field, so instead it's returning all hits that contain "H1N1" instead of just the ones in the title.

**Comment by sahmad998** [comment]
@rachaelcox that did it! thank you

**Comment by clauswilke** [comment]
@sahmad998 This is a good demonstration of why it is so important to have complete, reproducible code examples. The error is almost always in a different location than we initially think it is.
