### ISSUE TITLE
project 3, question 2

### ISSUE THREAD

**Issue by sahmad998** [clauswilke/SDS348_spring2020#36]
for part 2, I'm trying to do a literature-based search. so far my question has two parts: 
(1) Within the last decade(2010-2020), how many papers were published concerning the cephalic disorder anencephaly?
(2) What are the names of the authors, titles of the papers, and the sources of theses references?
based on this, the first part looks like this:
```
from Bio import Entrez, Medline
Entrez.email  = "saher.fatima98@utexas.edu"

handle = Entrez.esearch(
    db= "pubmed",
    term= "anencephaly[Title] AND 2010[Date - Publication]:2020[Date - Publication]",
    retmax = 10000
)

record = Entrez.read(handle)
handle.close()

pmid_list = record["IdList"]
print(pmid_list)
print(len(pmid_list))
```
this returned a list of IDs, and a length of 79 papers. however, when i try to do part two of the question, i get a giant HTTP error. the code is as such, and the error seems to occur at the retmode line:
```
from Bio import Medline
handle_paper = Entrez.efetch(
    db="pubmed", 
    id= "pmid_list",
    rettype="medline",
    retmode="text"
)

records = Medline.parse(handle_paper)
for record in records:
    print(record['AU'])
    print(record['TI'])
    print(record['SO'])
    print()
handle_paper.close()
```
i can't figure out what's wrong here, any tips?

**Comment by rachaelcox** [comment]
I think the problem is actually at this line: `id = "pmid_list"`. Since `pmid_list` is a variable and not a string, you need to remove the quotes. Try changing `"pmid_list"` to `pmid_list` and let me know if that works!

**Comment by sahmad998** [comment]
@rachaelcox that did it, thanks! i also wanted to double-check the first question with you- is it okay/not too similar to the COVID question? since the COVID one asked about how many total publications and mine asks about publications within the last decade, i thought it would be okay to do.

**Comment by rachaelcox** [comment]
I think the topic/direction of your question is fine, but perhaps too broad. You should make it more specific so your code will meet all of the requirements. Part 2 requires at least one list or dictionary, at least one `for` loop, at least one `if` statement, and at least one regular expression. **The regular expression has to be different than the regex used in Part 2 (i.e., you cannot extract the years again).** If this is your code so far, you still need an `if` statement and a regex. As long as you can check all those boxes you're good!
