### ISSUE TITLE
linear regression error

### ISSUE THREAD

**Issue by bbarrientos98** [clauswilke/SDS348_spring2020#4]
For project 2 i am trying to do a linear regression model but this is the error it shows whenever i attempt to run the code. I have also ran all the libraries at the top of the rmd file.

```r 
glm_out <- glm(
  type ~ pH + fixed_acidity + volatile_acidity + citric_acid,
  data = wine_features,
  family = binomial
)
```
The error message is: `Error in eval(family$initialize) : y values must be 0 <= y <= 1`

**Comment by clauswilke** [comment]
Please post a complete, reproducible example, including the code to read in the data, any libraries you are loading, and any data manipulation you may be doing before the `glm()` call. I should be able to copy your code into a new R session and reproduce the error.

**Comment by mciuliano** [comment]
if you wrap 'type' using the factor function it should fix it!
```r
glm_out <- glm(
  factor(type) ~ pH + fixed_acidity + volatile_acidity + citric_acid,
  data = wine_features,
  family = binomial
)
```
