### ISSUE TITLE
Project 3 Part 2 instructions

### ISSUE THREAD

**Issue by haemin-pdf** [clauswilke/SDS348_spring2020#40]
My code fetches papers with certain PubMed IDs that are stored in a list. This list was generated by performing a Entrez.esearch under certain conditions. Does this list count as a "meaningful" list? Or should I incorporate another list to meet the list requirement for the project?

```
handle = Entrez.esearch(db="pubmed",  # database to search
                        term="Matouschek A[Author]",  # search term
                        retmax=1000 # maximum number of results to return
                        )
record = Entrez.read(handle)
handle.close()

# search returns PubMed IDs (pmids)
pmid_list = record["IdList"]
```

```
handle2 = Entrez.efetch(db="pubmed",  # database to search
                        id=pmid_list,  # searching for IDs in pmid_list
                        rettype="medline" # returning "medline" datatype
                        )
record2 = Medline.parse(handle2) # storing the fetched data in record2
```

**Comment by clauswilke** [comment]
If all you do is receive a list from one function and hand it off to another function you haven't really used the list at all(\*), so I'd say this doesn't count.

(\*) To see that this is a trivial use of a list, consider that you don't need the variable `pmid_list` at all. In the second part of your code, you could simply write `id = record["IdList"]`, and that would actually make the code cleaner and simpler.
