### ISSUE TITLE
Project 3 Question 2

### ISSUE THREAD

**Issue by jiwanisahil** [clauswilke/SDS348_spring2020#41]
I wanted to know if my question for part 2 was fine. 

My question is: How many total publications in the PubMed database, published from 2000 to 2010 (inclusive), had the terms 'pandemic' or 'epidemic' in their abstracts?

I was able to get the total number and used a for loop, if statement, list, and regular expression. In the first part I extracted all the publications by date and then I used 

match = re.search("(epi|pan)demic",record['AB'])

to find the number of abstracts that had these terms in them. I was wondering if this question was alright to do?

**Comment by clauswilke** [comment]
I think you should pick something that is slightly more complex. Given your question, I don't even see that you need the various code constructs to answer it, the result should just pop right out of your initial PubMed search.
