### ISSUE TITLE
Project Part 2.

### ISSUE THREAD

**Issue by jennifernadasdy** [clauswilke/SDS348_spring2020#42]
My question: Find all articles where you have the word "epilepsy" in the title. Next, write in a file those articles' titles and affiliations where the last author is from one of the University of Texas' institute. 

My first, second, and third hits:
Assessment of Interlaboratory Variation in the Interpretation of Genomic Test Results in Patients With Epilepsy.--------Eugene McDermott Center for Human Growth and Development, University of Texas Southwestern Medical Center, Dallas.

Ictal and interictal source imaging on intracranial EEG predicts epilepsy surgery outcome in children with focal cortical dysplasia.--------Laboratory of Children's Brain Dynamics, Division of Newborn Medicine, Boston Children's Hospital, Harvard Medical School, Boston, MA, USA; Fetal-Neonatal Neuroimaging Developmental Science Center, Boston Children's Hospital, Harvard Medical School, Boston, MA, USA; Jane and John Justin Neurosciences Center, Cook Children's Health Care System, Fort Worth, TX, USA; 

From Genetic Testing to Precision Medicine in Epilepsy.--------Department of Pediatrics Division of Neurology, University of Texas Southwestern, Dallas, Texas, USA.

Problems: 
1. I use Spider and my code runs in Spider but only creates an empty text file when I run it Jupyter. Also, my lists seem empty or not complete. I don't get any error messages. So my code runs just fine in Syder but doesn't run in Jupyter. If I run it in Jupyter it runs without an error but I get an empty txt file. Also if I just print out the "university_list" I get an empty list.

2. My second hit should not be a hit. Why is that there?

3. I don't know how to edit the text in Jupyter. If I just add a new cell fill it with text and run it, I get an error message. I mean text as my answers to the questions and not the code. 

My code:

```{r}
from Bio import Entrez, Medline
Entrez.email = "jennifer.nadasdy@utexas.edu"
import re
handle_Epilepsy = Entrez.esearch(
        db = "pubmed",
        term = "Epilepsy[Title]",
        retmax = 10000)

record = Entrez.read(handle_Epilepsy)
handle_Epilepsy.close

Epilepsy_list = record["IdList"]

handle_list = Entrez.efetch(
    db = "pubmed",
    id=Epilepsy_list,
    rettype="medline")

records = Medline.parse(handle_list) 

university_list = []
title_list = []
for record in records:
    if "AD" in record:
        affi = record['AD']
        if len(affi) > 0:
            contrib = affi[-1]
            title = record['TI']
            
            match = re.search(r"University of Texas.*", contrib) 
            if match:
                university_list.append(title + "--------" + contrib)
            
handle_list.close()

#print(university_list)

f = open("texas.txt", "w")
for uni in university_list:
    f.write( uni + "\n")
f.close()
```

**Comment by clauswilke** [comment]
For text editing: Click on "Cell", "Cell Type", "Markdown"

Your code has at least one problem: `handle_Epilepsy.close` is missing parentheses.

Also, take a look at the contents of the `contrib` variable. I don't think it contains what you think it should.

Finally, your pubmed search yields over 50,000 results. Please choose something more restricted.

**Comment by jennifernadasdy** [comment]
My new code with a new "goal" is here:

```{r}
from Bio import Entrez, Medline
Entrez.email = "jennifer.nadasdy@utexas.edu"
import re
handle_subiculum = Entrez.esearch(
        db = "pubmed",
        term = "Subiculum[Title]",
        retmax = 1000)

record = Entrez.read(handle_subiculum)
handle_subiculum.close()

Epilepsy_list = record["IdList"]

handle_list = Entrez.efetch(
    db = "pubmed",
    id=Epilepsy_list,
    rettype="medline")

records = Medline.parse(handle_list) 

university_list = []
title_list = []
for record in records:
    if "AD" in record:
        affi = record['AD']
        if len(affi) > 0:
            contrib = affi[-1]
            title = record['TI']
            
            match = re.search(r"University of Texas.*", contrib) 
            if match:
                university_list.append(title + "---" + contrib)
            
handle_list.close()

print(university_list)
```

I checked the second hit of the original code, and actually that was correct but for some reason in the file, UT Arlington did not appear. Maybe there were too many affiliations? 

If you still think that my code is wrong then could you please more specific?  How can I fix it and what is wrong with it? 

The code is still not running in Jupyter. I can't see why.

**Comment by clauswilke** [comment]
Again, you need to check the content of the variable `contrib`. You need to check it on the system where it doesn't work. It's possible that it's different in Jupyter and in your local install, e.g. if you have different library versions.

**Comment by rachaelcox** [comment]
More specifically, use `print` to troubleshoot your problem variables. For instance:

```python
for record in records:
    if "AD" in record:
        affi = record['AD']
        if len(affi) > 0:
            contrib = affi[-1]
            print('this is what the contrib variable looks like: ' + contrib)
```

**Comment by jennifernadasdy** [comment]
Yes, I noticed that instead of reading the last affiliation item, my program reads only the last character. How do I extract the last affiliation record instead of the last character when using contrib = affi[-1]  ?

**Comment by clauswilke** [comment]
You'll have to figure that one out on your own or change your question/problem formulation so it's not an issue.

As a hint (though I haven't tested this, so may be wrong), you may find the `.split()` function helpful: https://www.w3schools.com/python/ref_string_split.asp
