### ISSUE TITLE
Project 3 General Question

### ISSUE THREAD

**Issue by scottburns1082** [clauswilke/SDS348_spring2020#43]
Hello,

For project 3,  I noticed that there is not  an introduction section on the HTML file. However, there is an introduction section on the rubric. I assume we still need to do an introduction? If so, where can I find the appropriate information on the databases? 

Best,

Scott

**Comment by rachaelcox** [comment]
This is the project 3 rubric, it does not contain an introduction section: https://wilkelab.org/classes/SDS348/2020_spring/projects/project3_rubric.pdf
