### ISSUE TITLE
Project 3 Bio Module Issue

### ISSUE THREAD

**Issue by joyomorojie11** [clauswilke/SDS348_spring2020#44]
For the project, my notebook in unable to "find" the Bio Module and I have literally ***tried*** everything I could think of. I keep getting this. 

```python
from Bio import Entrez, Medline
import re

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-817d29293b0a> in <module>()
----> 1 from Bio import Entrez, Medline
      2 import re

ModuleNotFoundError: No module named 'Bio'
```
I have tried !pip, !apt-get, downloading biopython, I've changed Bio to bio and then it doesn't recognize Entrez. I didn't have this problem for HW 9.

**Comment by clauswilke** [comment]
I'm sorry, we cannot trouble-shoot local installs, and in fact we discourage that you use a local install for assignments. Please do this on one of the educomps.

**Comment by rachaelcox** [comment]
> I'm sorry, we cannot trouble-shoot local installs, and in fact we discourage that you use a local install for assignments. Please do this on one of the educomps.

Based on homework submissions, I actually think this is from Google Colaboratory. Is that right @joyomorojie11 ?

**Comment by joyomorojie11** [comment]
yes I was using the google colab but I switched to the educomp, which is working.

**Comment by rachaelcox** [comment]
Good! I'll close this issue then; open a new one if you run into more issues.
