### ISSUE TITLE
project 3, regex and if statement 

### ISSUE THREAD

**Issue by sahmad998** [clauswilke/SDS348_spring2020#45]
this is my question for the last part of the second question:
```
Anencephaly is known to be a neural tube defect that occurs when the cranial end of the neural tube fails to close completely. There are a variety of things that can lead to this- such as environmental exposure to toxins, dietary deficiencies (in particular, folic acid) and gentic mutations. How many of the papers published over the last decade point to genetics as the cause of this neural tube defect in their abstracts?
```

i already have a for statement and dictionary done for this question. i just wanted to confirm if this code satisfies both the regex and if statement requirements. :

```from Bio import Medline
handle_abstract = Entrez.efetch(
    db="pubmed",
    id = pmid_list,
    rettype= "medline",
    retmode="text",
    retmax=100
)

records = Medline.parse(handle_abstract)

ab_count = 0

for record in records:
    if "AB" in record:
        match = re.search(r"gene(|tic)(|ally)", record["AB"])
        if match: 
            ab_count += 1
handle_abstract.close()

print(ab_count, 'of the abstracts contain the words "genetic or genetically"')

```
```
22 of the abstracts contain the words "genetic or genetically"
```

**Comment by clauswilke** [comment]
Yes. However, your regular expression isn't quite right. Try it in pythex.org to see.

**Comment by sahmad998** [comment]
is this better? it worked in pythex.org
```
for record in records:
    if "AB" in record:
        match = re.search(r"gene(|tic)", record["AB"])
        if match: 
            ab_count += 1
handle_abstract.close()
```

**Comment by clauswilke** [comment]
I don't see it working. The "tic" part is not matching.
<img width="710" alt="Screen Shot 2020-05-05 at 4 24 38 PM" src="https://user-images.githubusercontent.com/4210929/81117600-fad65d00-8eec-11ea-9fb7-9ac467904b64.png">

**Comment by clauswilke** [comment]
You're essentially just matching on "gene", which you could do by writing `match = re.search(r"gene", record["AB"])`.

**Comment by sahmad998** [comment]
![image](https://user-images.githubusercontent.com/62726143/81118638-e1ceab80-8eee-11ea-9fc4-fa43fafe27fb.png)

got it, thanks!

**Comment by rachaelcox** [comment]
FYI, something to keep in mind:
![image](https://user-images.githubusercontent.com/42787920/81120745-f6ad3e00-8ef2-11ea-9672-057cc84055dd.png)
