### ISSUE TITLE
Problem 1 Question + Code Issue 

### ISSUE THREAD

**Issue by thomaspvargas** [clauswilke/SDS348_spring2020#46]
I have a question regarding the first problem of project 3. The problem asks how many titles per year were published on H1N1 and Covid-19. How far back are we supposed to go? For example with h1n1 it could go back almost 15 years. Are we supposed to type this all into re.search and change it for each year since the inception of the virus? Or is there a better way of doing this. I have attached a screenshot of how I am approaching the problem. Also, everytime I approach the problem in this manner, my counter doesn't work despite me typing it in exactly the same way as the homework. This problem has also occurred in the past on my homework and its popping up again on the project so I'm struggling with it. Notice how the counter stays at 0 for some reason. Thank you :) 
![Screenshot (248)](https://user-images.githubusercontent.com/49924374/81084515-94851680-8ebb-11ea-8302-872824259e20.png)

**Comment by rachaelcox** [comment]
Actually, publications resulting from the search "H1N1[Title]" go back nearly 50 years! You are supposed to capture them all in the `pmid_list` variable, then write a regular expression that captures the year in any format (see https://github.com/clauswilke/SDS348_spring2020/issues/29). As a hint, the year is always a 4 digit number.

As far as your counter, you need to set up a dictionary that holds years as dictionary keys and the counts as values for each year. There are examples for how to set up a dictionary that counts the number of occurrence for each key: 
- Problem 1c of https://wilkelab.org/classes/SDS348/2020_spring/worksheets/class18_solutions.html
- Problem 3 of https://wilkelab.org/classes/SDS348/2020_spring/labs/lab10-solution.html
- Problem 2 of https://wilkelab.org/classes/SDS348/2020_spring/homeworks/HW8-solution.html

**Comment by rachaelcox** [comment]
Also, as a side note, if you submit questions in the future, copy your code directly into Github and fence it with back ticks (an example is here https://github.com/clauswilke/SDS348_spring2020 under "asking questions about python"). 

This makes it much easier for us to read your code and/or copy it to our own notebooks to run!

**Comment by thomaspvargas** [comment]
Awesome thank you for the help!
