### ISSUE TITLE
Project 3 Q1

### ISSUE THREAD

**Issue by joyomorojie11** [clauswilke/SDS348_spring2020#47]
I'm having trouble with the publication date question and I'm not sure how to go about it. 

```python
Entrez.email = "joyomorojie@utexas.edu"

handle = Entrez.esearch(db="pubmed",  # database to search
                        term="SARS-CoV-2",  # search term
                        id= "pmid_list",
                        rettype= "medline",
                        retmax=10000 # maximum number of results to return
                        )
records = Medline.parse(handle)
record = Entrez.read(handle)

dp_list = 0

for record in records:
    #dp_list = record['DP']
    for DP in record: 
         match = re.search(r'(2017)', record['DP'])
    if match:
         dp_list += 1   
            
print('total date of publication=', dp_list)
    
pmid_list = record["IdList"]
print('total # of papers =', len(pmid_list))
    
handle.close()
```
I keep getting answer of 0 for publication.

**Comment by clauswilke** [comment]
Please take a look at Problem 3 Homework 9:
https://wilkelab.org/classes/SDS348/2020_spring/homeworks/HW9-solution.html

**Comment by rachaelcox** [comment]
A few things: (1) make you are using a regular expression that matches *any year*, not a specific one--it's not guaranteed that publications exist in 2017; (2) evaluate carefully if you should be using a `for` loop or an `if` statement (see the HW solution Dr. Wilke linked), improper constructs will return bad results; (3) if you haven't noticed yet, your indentation if off. This is your code:

```python
for record in records:
    #dp_list = record['DP']
    for DP in record: 
         match = re.search(r'(2017)', record['DP'])
    if match:
         dp_list += 1
```

This code will loop through all the records and only evaluate whether the last record has a match. Instead, to evaluate a match for each record:

```python
for record in records:
    #dp_list = record['DP']
    for DP in record: 
         match = re.search(r'(2017)', record['DP'])
         if match:
             dp_list += 1
```

Note, I've only corrected the indentation. Think about points (1) and (2) for other parts that need to be fixed.

**Comment by joyomorojie11** [comment]
Last question. I put this in the pythrex and it worked but my out put is still 0

```python 
match = re.search(r"20(|17|18|19|20)", record["DP"].lower())
```
should I be accounting for white spaces?

**Comment by rachaelcox** [comment]
Did you fix the indentation or the loop I mentioned above? Please post all of your code.

Your regular expression still only matches 2017, 2018, 2019 and 2020. You want to match all years, so all of the 1900s and 2000s. Click on the "regular expression cheat sheet" at https://pythex.org/ to figure out how to match any digit.

**Comment by joyomorojie11** [comment]
```python
handle = Entrez.esearch(db="pubmed",  # database to search
                        term="SARS-CoV-2",  # search term
                        id= pmid_list,
                        rettype= "medline",
                        retmax=10000 # maximum number of results to return
                        )
records = Medline.parse(handle)
record = Entrez.read(handle)

dp_count = 0

for record in records: 
    if "DP" in records:
        match = re.search(r"20(|17|18|19|20)", record["DP"].lower())
    if match: 
        dp_count += 1
handle.close()

print(dp_count, '# of publications')
```
i know my regex is wrong but i just wanted to test if it would pick up any documentation

**Comment by clauswilke** [comment]
After `esearch()`, you have to do `efetch()` to retrieve the record you want to analyze. Check Problems 2 and 3 in homework 9: https://wilkelab.org/classes/SDS348/2020_spring/homeworks/HW9-solution.html

**Comment by joyomorojie11** [comment]
Thank you for the help!
