### ISSUE TITLE
Project 3 Question 2 Question

### ISSUE THREAD

**Issue by thomaspvargas** [clauswilke/SDS348_spring2020#49]
Hello! I am trying to find out if there is any overlap between SARS-CoV authors and SARS-CoV-2 authors. I am trying to append a list called SARS_authors. When I run the code it stops after printing the total number of publications mentioning SARS-CoV. How do I go about appending this list correctly? 
```
from Bio import Entrez, Medline
import re
Entrez.email = "thomaspvargas@utexas.edu"
handle = Entrez.esearch(
    db="pubmed",  
    term="SARS-CoV", 
    retmax=10000  
)
record = Entrez.read(handle)

SARS_list = record["IdList"]
print("Total number of publications with the term of SARS-CoV is:", len(SARS_list))
handle2 = Entrez.efetch(db="pubmed", id=SARS_list, rettype="medline", retmode="text")
records = Medline.parse(handle2)
SARS_authors = []
for record in records:
    if "AU" in record:
        SARS_authors.append(record['AU'])
    else:
        pass
handle2.close()
print((SARS_authors))
```

**Comment by thomaspvargas** [comment]
The code actually does print, however there is a lot of overlap in the authors, how would I go about removing repeats of authors from the list?

**Comment by clauswilke** [comment]
You need to use a dictionary instead of a list, similarly to how we have written code in class to count letters.

**Comment by thomaspvargas** [comment]
Oh okay that makes sense. Thank you!
