### ISSUE TITLE
Grad Student Project Questions

### ISSUE THREAD

**Issue by TongruiLi** [clauswilke/SDS348_spring2020#5]
1. I was wondering what kind of dataset would be considered as sufficient for the project?

2. Can we use python instead of r?

**Comment by clauswilke** [comment]
1. You can use any dataset you want. It just needs some minimum complexity so you can do a meaningful analysis. I suppose the absolute minimum is three observations and three variables (i.e., three rows, three columns).

2. Yes.

**Comment by TongruiLi** [comment]
Thanks!
