### ISSUE TITLE
HW8 definition of whitespace

### ISSUE THREAD

**Issue by TongruiLi** [clauswilke/SDS348_spring2020#6]
As stated in the problem:

"Print out the sequence of the gene such that all nucleotides have been converted to uppercase and **white space** has been removed."

I was wondering what constitutes as white space? If it is referring to " " I believe that the file naturally does not have any.

**Comment by rachaelcox** [comment]
So the unaltered format of the given sequence looks like this:
![il6_sequence_unformatted](https://user-images.githubusercontent.com/42787920/78826314-eadb6400-79a6-11ea-9e99-059af1de4594.PNG)

And the final version of it should look like this:
![il6_sequence_formatted](https://user-images.githubusercontent.com/42787920/78826357-fe86ca80-79a6-11ea-97e5-fa806602e6c2.PNG)

The '\n' become apparent when you used `readlines()` to read in the sequence from the .txt file.

**Comment by TongruiLi** [comment]
Thanks for the clarification!
