### ISSUE TITLE
uploading files

### ISSUE THREAD

**Issue by emm3777** [clauswilke/SDS348_spring2020#7]
![Screenshot (1)](https://user-images.githubusercontent.com/63424679/78935575-9d2c2d80-7a72-11ea-9eb9-cb802fa2cc64.png)

I have been trying to open the file for my homework and it says I do not have the file. I have downloaded it onto my computer, and uploaded it to my jupyter notebook with the same names, but it can not find it.

**Comment by AENeely** [comment]
The txt file needs to be in the same folder as the juptyer notebook you are working on.  Assuming the 'HW8' file is in your 'Homeworks' folder, try moving the 'IL6_gene_human_lower.txt' file into that folder as well before running that code.

**Comment by rachaelcox** [comment]
Ashley has the right of it, you need to move the 'IL6_gene_human_lower.txt' file into the same folder as your homework. Did that fix your issue?

**Comment by emm3777** [comment]
That worked! Thank You
