### ISSUE TITLE
error with .strip()

### ISSUE THREAD

**Issue by mciuliano** [clauswilke/SDS348_spring2020#8]
For question 1 on the homework, when I try to use `.strip()` to remove the whitespace it keeps giving me this error:
AttributeError: 'list' object has no attribute 'strip'

``` python
with open("IL6_gene_human_lower.txt", "r") as infile:
    line = infile.readlines()
    print(line.strip())
```

**Comment by rachaelcox** [comment]
Hi Maria,

The error is giving you a hint here. If you `print(line)`, it actually gives you a list of lines. To access each element in that list and `strip()` it, you will need to use a `for` loop. Let me know if that helps.

**Comment by mciuliano** [comment]
yes that helped, thank you !!
