### ISSUE TITLE
Removing \n

### ISSUE THREAD

**Issue by jiwanisahil** [clauswilke/SDS348_spring2020#9]
I have a question about problem 3 on HW 8. I believe I got the correct code because I'm getting the correct output. However, when I run the program, 'AA\n' shows up as the final 3-mer but when I look at the text file, there is not sign of a \n to remove. I'm not sure if I'm doing something wrong but I attached my code so you can see what I mean. 

`covid19 = "covid19_genome.txt"
#the name of the file we want to open

file_handle2 = open(covid19, "r") #open file as read only
file_lines2 = file_handle2.read() #read contents of the file`

Attached is the end of my output:
![Screen Shot 2020-04-10 at 2 06 47 PM](https://user-images.githubusercontent.com/62567858/79024057-ad0d4580-7b36-11ea-8ce3-795bf32ccbb5.png)

**Comment by rachaelcox** [comment]
Hi Sahil,

The `\n` character is hidden when opening the .txt file in Jupyter (or another application such as Notepad), but it is definitely there. You can remedy this by also applying the `.strip()` function when reading in the contents of the file.

Potentially useful reference: https://wilkelab.org/classes/SDS348/2020_spring/worksheets/class18_solutions.html

**Comment by clauswilke** [comment]
In fact, you can see the newline character by printing the genome inside a list (i.e., putting it into `[ ]` before printing).

``` python
with open("covid19_genome.txt") as in_handle:
    genome = in_handle.read()

print([genome[-10:]])
## ['AAAAAAAAA\n']
```
